# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI1_Prueba.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Prueba(object):
    def setupUi(self, Prueba):
        Prueba.setObjectName("Prueba")
        Prueba.resize(1124, 704)
        Prueba.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(Prueba)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(240, 590, 191, 71))
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(460, 590, 191, 71))
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(670, 590, 191, 71))
        self.lcdNumber_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_3.setSmallDecimalPoint(False)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 140, 911, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        Prueba.setCentralWidget(self.centralwidget)

        self.retranslateUi(Prueba)
        QtCore.QMetaObject.connectSlotsByName(Prueba)

    def retranslateUi(self, Prueba):
        _translate = QtCore.QCoreApplication.translate
        Prueba.setWindowTitle(_translate("Prueba", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Prueba", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Prueba", "Tab 2"))
