# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Unidades compartidas\Comunicaciones Mars-Rover M2\Programas\Python\GUI\QT\GUI1_Prueba.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from PyQt5 import QtCore, QtGui, QtWidgets
import sys 
from PyQt5 import QtCore, QtGui, QtWidgets
from Camera import *
import cv2

class Ui_Prueba(object):
    def setupUi(self, Prueba):
        self.i = 0
        Prueba.setObjectName("Prueba")
        Prueba.resize(1124, 704)
        Prueba.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(Prueba)
        self.centralwidget.setObjectName("centralwidget")
        
        self.labelCamera = QtWidgets.QLabel(self.centralwidget)
        self.labelCamera.setGeometry(412,100,640,480)
        self.labelCamera.setFrameStyle(QtWidgets.QFrame.StyledPanel)
        
        self.CameraThreadW = CameraThread()
        self.CameraThreadW.start()
        self.CameraThreadW.ImageUpdate.connect(self.ImageUpdateSlot)

        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 440, 191, 71))
        self.lcdNumber.setStyleSheet("gridline-color: rgb(85, 255, 255);")
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(10, 530, 191, 71))
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(10, 620, 191, 71))
        self.lcdNumber_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber_3.setSmallDecimalPoint(False)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        Prueba.setCentralWidget(self.centralwidget)

        self.retranslateUi(Prueba)
        self.timer = QtCore.QTimer()
        self.timer.setInterval(10)
        self.timer.timeout.connect(self.lcd_CountUp)
        self.timer.start()
        
        QtCore.QMetaObject.connectSlotsByName(Prueba)

    def retranslateUi(self, Prueba):
        _translate = QtCore.QCoreApplication.translate
        Prueba.setWindowTitle(_translate("Prueba", "Comunicaciones"))

    def ImageUpdateSlot(self, ImageCamera):
        self.labelCamera.setPixmap(QtGui.QPixmap.fromImage(ImageCamera))
    
    def set_lcd_number_1(self, value):
        self.lcdNumber.display(value)
    def set_lcd_number_2(self, value):
        self.lcdNumber_2.display(value)
    def set_lcd_number_3(self, value):
        self.lcdNumber_3.display(value)

    def lcd_CountUp(self):
        self.i= self.i + 1
        self.set_lcd_number_1(self.i)
        self.set_lcd_number_2(self.i)
        self.set_lcd_number_3(self.i)
        if self.i == 1000:
            self.i= 0


# class VideoThread(QtCore.QThread):
#     ImageUpdate = QtCore.pyqtSignal(QtGui.QImage)


class Ventana(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Prueba()
        self.ui.setupUi(self)
        
        Image = QtGui.QImage('image.jpg')
        sImage = Image.scaled(QtCore.QSize(1124,704))
        palette = QtGui.QPalette()
        palette.setBrush(10,QtGui.QBrush(sImage))
        self.setPalette(palette)

    

