# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rover.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    datos_recibidos = ''
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(426, 550)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(300, 480, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 480, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(150, 40, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(290, 40, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(150, 110, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(290, 110, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(150, 180, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(30, 150, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(290, 180, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(30, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(170, 230, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(30, 310, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(230, 310, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(130, 390, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(30, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(170, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(310, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(170, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(30, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(310, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(30, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(170, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(310, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(30, 260, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(170, 260, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(230, 340, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(30, 340, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(130, 420, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        #---
        self.timer = QtCore.QTimer()
        self.timer.setInterval(10)
        self.timer.timeout.connect(self.seeData2)
        self.timer.start()

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close)
        self.pushButton_2.clicked.connect(self.seeData)
        #self.seeData2()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Datos del Rover"))
        self.pushButton.setText(_translate("Form", "Salir"))
        self.label.setText(_translate("Form", "ACELEROMETRO"))
        self.pushButton_2.setText(_translate("Form", "Ver"))
        self.label_2.setText(_translate("Form", "X: "))
        self.label_3.setText(_translate("Form", "Y: "))
        self.label_4.setText(_translate("Form", "Z: "))
        self.label_5.setText(_translate("Form", "Y: "))
        self.label_6.setText(_translate("Form", "GIROSCOPIO"))
        self.label_7.setText(_translate("Form", "Z: "))
        self.label_8.setText(_translate("Form", "X: "))
        self.label_9.setText(_translate("Form", "Y: "))
        self.label_10.setText(_translate("Form", "MAGNETOMETRO"))
        self.label_11.setText(_translate("Form", "Z: "))
        self.label_12.setText(_translate("Form", "X: "))
        self.label_14.setText(_translate("Form", "PRESION"))
        self.label_15.setText(_translate("Form", "TEMPERATURA"))
        self.label_16.setText(_translate("Form", "LONGITUD"))
        self.label_17.setText(_translate("Form", "LATITUD"))
        self.label_18.setText(_translate("Form", "ERROR"))
        self.label_13.setText(_translate("Form", "ax"))
        self.label_19.setText(_translate("Form", "ay"))
        self.label_20.setText(_translate("Form", "az"))
        self.label_21.setText(_translate("Form", "gy"))
        self.label_22.setText(_translate("Form", "gx"))
        self.label_23.setText(_translate("Form", "gz"))
        self.label_24.setText(_translate("Form", "mx"))
        self.label_25.setText(_translate("Form", "my"))
        self.label_26.setText(_translate("Form", "mz"))
        self.label_27.setText(_translate("Form", "p"))
        self.label_28.setText(_translate("Form", "t"))
        self.label_29.setText(_translate("Form", "lat"))
        self.label_30.setText(_translate("Form", "lon"))
        self.label_31.setText(_translate("Form", "error"))

    def seeData(self):
        count = 0
        

    def seeData2(self):
        _translate = QtCore.QCoreApplication.translate
        data = puertoSerial.collect_data()
        if data != None:
            self.datos_recibidos = self.datos_recibidos + data
            [cadenaExtraida, mensajeCompleto, self.datos_recibidos] = json_v3.CORTAR_JSON(self.datos_recibidos)
            if (mensajeCompleto):
                error = json_v3.REVISAR_JSON(cadenaExtraida)
                if (error):
                    [nombres, valores] = json_v3.SEPARAR_MENSAJE_JSON(cadenaExtraida)
                    self.label_13.setText(_translate("Form", str(valores[0])))
                    self.label_19.setText(_translate("Form", str(valores[1])))
                    self.label_20.setText(_translate("Form", str(valores[2])))
                    self.label_21.setText(_translate("Form", str(valores[3])))
                    self.label_22.setText(_translate("Form", str(valores[4])))
                    self.label_23.setText(_translate("Form", str(valores[5])))
                    self.label_24.setText(_translate("Form", str(valores[6])))
                    self.label_25.setText(_translate("Form", str(valores[7])))
                    self.label_26.setText(_translate("Form", str(valores[8])))
                    self.label_27.setText(_translate("Form", str(valores[9])))
                    self.label_28.setText(_translate("Form", str(valores[11])))
                    self.label_29.setText(_translate("Form", str(valores[12])))
                    self.label_30.setText(_translate("Form", str(valores[13])))
                    self.label_31.setText(_translate("Form", str(valores[14])))



if __name__ == "__main__":
    import Monitor_serial
    import sys
    import json_v3
    import time
    python_version = sys.version[0]

    if len(sys.argv) != 2:
        print ("Wrong Number of Arguments!")
        print ("Please use format: python SensorTile_Animation_args.py SerialAddress")
    else:
        address = sys.argv[1]

        if python_version == "2":
            python3 = False
        else:
            python3 = True

    baud_rate = 115200
    timeout = 2
#    tt = True

    puertoSerial = Monitor_serial.serial_Monitor(address, baud_rate, timeout, python3)
    puertoSerial.init_connection()

	
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
    puertoSerial.close_connection()
    